stages:
  clean:
    cmd: python src/clean_data.py
    deps:
    - data/raw/events.csv
    outs:
    - data/clean/events.csv
  transform:
    cmd: python src/transform_data.py
      data/transformed/events.csv
    deps:
    - data/clean/events.csv
    outs:
    - data/transformed/events.csv
  features:
    cmd: python src/feature_data.py data/transformed/events.csv data/features/events.csv
    deps:
    - data/transformed/events.csv
    - src/feature_data.py
    outs:
    - data/features/events.csv
